In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\User\Downloads\Admission_Predict.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
Serial No.           400 non-null int64
GRE Score            400 non-null int64
TOEFL Score          400 non-null int64
University Rating    400 non-null int64
SOP                  400 non-null float64
LOR                  400 non-null float64
CGPA                 400 non-null float64
Research             400 non-null int64
Chance of Admit      400 non-null float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB


In [4]:
df.drop('Serial No.',axis =1 , inplace =True)
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [5]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR   \
count  400.000000   400.000000         400.000000  400.000000  400.000000   
mean   316.807500   107.410000           3.087500    3.400000    3.452500   
std     11.473646     6.069514           1.143728    1.006869    0.898478   
min    290.000000    92.000000           1.000000    1.000000    1.000000   
25%    308.000000   103.000000           2.000000    2.500000    3.000000   
50%    317.000000   107.000000           3.000000    3.500000    3.500000   
75%    325.000000   112.000000           4.000000    4.000000    4.000000   
max    340.000000   120.000000           5.000000    5.000000    5.000000   

             CGPA    Research  Chance of Admit   
count  400.000000  400.000000        400.000000  
mean     8.598925    0.547500          0.724350  
std      0.596317    0.498362          0.142609  
min      6.800000    0.000000          0.340000  
25%      8.170000    0.000000          0.640000  
50%      8.610000    1.000000          0.730000  
75%      9.062500    1.000000          0.830000  
max      9.920000    1.000000          0.970000

In [9]:
df['Admission'] = [ 1 if x >= 0.785 else 0 for x in df['Chance of Admit ']]
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   Admission  
0              0.92          1  
1              0.76          0  
2              0.72          0  
3              0.80          1  
4              0.65          0

In [10]:
df.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.835977           0.668976  0.612831   
TOEFL Score         0.835977     1.000000           0.695590  0.657981   
University Rating   0.668976     0.695590           1.000000  0.734523   
SOP                 0.612831     0.657981           0.734523  1.000000   
LOR                 0.557555     0.567721           0.660123  0.729593   
CGPA                0.833060     0.828417           0.746479  0.718144   
Research            0.580391     0.489858           0.447783  0.444029   
Chance of Admit     0.802610     0.791594           0.711250  0.675732   
Admission           0.695218     0.703477           0.632065  0.575947   

                       LOR       CGPA  Research  Chance of Admit   Admission  
GRE Score          0.557555  0.833060  0.580391          0.802610   0.695218  
TOEFL Score        0.567721  0.828417  0.489858          0.791594   0.703477  
University Rating  0.660123  0.746479  0.447783          0.711250   0.632065  
SOP                0.729593  0.718144  0.444029          0.675732   0.575947  
LOR                1.000000  0.670211  0.396859          0.669889   0.520723  
CGPA               0.670211  1.000000  0.521654          0.873289   0.740933  
Research           0.396859  0.521654  1.000000          0.553202   0.530209  
Chance of Admit    0.669889  0.873289  0.553202          1.000000   0.771360  
Admission          0.520723  0.740933  0.530209          0.771360   1.000000

In [25]:
df.drop(['Chance of Admit '],axis =1, inplace =True)

In [26]:
X = df.loc[:,df.columns != 'Admission']
Y = df['Admission']

In [27]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
X = preprocessing.StandardScaler().fit(X).transform(X)

In [28]:
X

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [29]:
Y = Y.values

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state =0)

In [31]:
from sklearn.linear_model import LogisticRegression
Lr = LogisticRegression().fit(X_train,Y_train)


C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [32]:
y_hat = Lr.predict(X_test)

In [33]:
y_hat

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [34]:
Y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [36]:
score = accuracy_score(Y_test,y_hat)
score

0.8875

In [37]:
y_hat_probability = Lr.predict_proba(X_test)
y_hat_probability

array([[9.22990532e-01, 7.70094683e-02],
       [9.11817165e-01, 8.81828350e-02],
       [4.58949100e-01, 5.41050900e-01],
       [9.95266714e-01, 4.73328572e-03],
       [9.17533400e-01, 8.24666003e-02],
       [9.97986389e-01, 2.01361115e-03],
       [9.18230331e-01, 8.17696685e-02],
       [9.91132488e-01, 8.86751228e-03],
       [3.48139366e-02, 9.65186063e-01],
       [9.44133878e-03, 9.90558661e-01],
       [9.99707581e-01, 2.92419358e-04],
       [2.12800630e-02, 9.78719937e-01],
       [9.13852158e-01, 8.61478421e-02],
       [9.99972796e-01, 2.72044576e-05],
       [7.54458688e-02, 9.24554131e-01],
       [9.95193659e-01, 4.80634134e-03],
       [9.94779532e-01, 5.22046809e-03],
       [2.40563203e-01, 7.59436797e-01],
       [9.98643318e-01, 1.35668204e-03],
       [8.82326688e-01, 1.17673312e-01],
       [2.26674970e-02, 9.77332503e-01],
       [1.40292619e-01, 8.59707381e-01],
       [9.79704543e-01, 2.02954569e-02],
       [9.99976994e-01, 2.30060614e-05],
       [2.957852

In [40]:
print(classification_report(Y_test,y_hat))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92        55
           1       0.81      0.84      0.82        25

    accuracy                           0.89        80
   macro avg       0.87      0.87      0.87        80
weighted avg       0.89      0.89      0.89        80



In [41]:
confusion_matrix(Y_test,y_hat,labels=[1,0])

array([[21,  4],
       [ 5, 50]], dtype=int64)